// 샘플 단어 데이터
const unit1 = {
    "provide": "공급하다, 준비하다",
    "develop": "개발하다, 발달하다",
    "service": "서비스, 봉사, 공공 업무",
    "inform": "알리다, 통지하다",
    "relationship": "관계",
    "improve": "향상시키다, 향상하다",
    "individual": "개인, 개인의, 개인적인, 각각의",
    "require": "필요로 하다, 요구하다",
    "advise": "조언하다, 충고하다",
    "social": "사회의, 사교적인",
    "amount": "총액, 총계, 양, 총계가 ~이 되다",
    "behave": "(예의바르게) 행동하다",
    "employ": "고용하다, 기술, 방법등을 쓰다",
    "attitude": "태도, 입장",
    "research": "연구, 연구하다, 조사하다",
    "audience": "청중, 관객",
    "volunteer": "자원봉사, 지원자, 자발적으로 ~하다",
    "influence": "영향, 영향을 미치는 것(사람), 영향을 끼치다",
    "terrible": "끔찍한, 무서운",
    "opportunity": "기회",
    "ability": "능력",
    "expense": "비용, 지출",
    "local": "지방의, 지역의, 장소의",
    "involve": "포함하다, 관련되다, (사건 등에) 말려들게 하다",
    "stress": "강조, 스트레스, 강조하다, 압력을 주다",
    "therefore": "그러므로, 그 결과",
    "positive": "긍정적인, 확신하는",
    "average": "평균, 평균의, 평균~이다",
    "ride": "탈것을 타다, 타기, 타고가기",
    "encourage": "촉구하다, 격려하다",
    "determine": "결심하다, 결정하다",
    "international": "국제의, 국제적인",
    "consume": "소비하다, 먹다, 마시다",
    "impress": "깊은 인상을 주다, 감동시키다",
    "object": "물체, 목표, 반대하다",
    "available": "이용하능한, 쓸모있는",
    "contain": "함유하다, 포함하다, 억제하다",
    "recognize": "인지하다, 인정하다",
    "material": "재료, 물질, 물질의",
    "comfort": "편안하게 하다, 위로하다, 편안, 위로"
};
const unit2 = {
    "emotion": "감정",
    "amaze": "놀라게 하다",
    "reduce": "줄이다, 낮추다",
    "discover": "발견하다",
    "decide": "결심하다, 결정하다",
    "benefit": "이익, 이익이 되다",
    "affect": "영향, 영향을 미치는 것(사람), 영향을 끼치다",
    "level": "수준, 수평, 수평의 , 평평하게 하다",
    "chemistry": "화학, 교감",
    "immediate": "직접의, 즉각적인",
    "thus": "그러므로, 따라서",
    "proper": "적절한, 알맞은",
    "performance": "공연, 성적, 성과",
    "essence": "(사물의) 본질, 정수",
    "economic": "경제의, 경제학의",
    "cell": "세포, 작은 방, 독방",
    "focus": "초점, 집중하다",
    "issue": "논란거리, 발행, 발행물, 발행하다",
    "participate": "참여하다, 참가하다(in)",
    "demand": "요구하다, 수요",
    "occur": "(사건이)일어나다, 발생하다",
    "complex": "복잡한, 복합체",
    "define": "정의하다, 한계 짓다, 한정하다",
    "proud": "자랑스러워하는, 자만하는",
    "aware": "인지하는, 알고 있는",
    "contact": "접촉, 접촉하다",
    "profession": "직업, 직종",
    "detail": "세부, 상술하다",
    "approach": "접근하다, 접근",
    "career": "직업, 경력",
    "package": "꾸러미, 포장, 포장하다",
    "disappear": "사라지다",
    "novel": "(장편)소설, 참신한",
    "secure": "안전한, 안전하게 하다, 확보하다",
    "fashion": "유행, 패션, 방식, 만들어내다",
    "despite": "~에도 불구하고",
    "background": "배경, 배경 지식, 이유",
    "solution": "해결, 해결책, 용액",
    "generate": "일으키다, 발생시키다",
    "eventually": "결국"
};
const unit3 = {
    "decrease": "줄다[감소하다], 줄이다, 감소",
    "recycle": "재활용하다",
    "desire": "욕망, 욕구, 바라다",
    "balance": "균형, 은행 잔고, 균형을 이루다",
    "negative": "부정적인",
    "follow": "따라가다, (규칙을) 따르다",
    "account": "은행 계좌, 이야기, 설명하다",
    "publish": "발표하다, 출판하다",
    "occasion": "경우, 특별한 일",
    "replace": "대체하다",
    "constant": "일정한, 불변의, (수학에서의) 상수",
    "expert": "전문가",
    "term": "기간, 학기, 용어",
    "relieve": "경감하다, 안도시키다",
    "describe": "묘사하다, 표현하다",
    "biology": "생물학",
    "due": "만기의, ~하기로 되어 있는",
    "equipment": "장치, 장비",
    "congratulate": "축하하다",
    "birth": "탄생",
    "compose": "구성하다, 작곡하다, 작문하다",
    "genius": "천재, 천재성",
    "reflect": "반영하다, 반사하다, 숙고하다",
    "cause": "~의 원인이 되다, 야기하다, 원인",
    "frequent": "빈번한, (장소·모임에) 자주 가다",
    "factor": "요인, 요소",
    "extreme": "극단의, 극단",
    "tend": "(~하는) 경향이 있다 (to), 돌보다",
    "politics": "정치, 정치학",
    "insist": "주장하다",
    "extend": "연장하다, 넓히다",
    "lonely": "외로운",
    "habitat": "서식지, 주거지",
    "mental": "정신의",
    "steady": "안정된, 한결같은, 꾸준한",
    "exchange": "교환하다",
    "active": "활동적인, 적극적인",
    "species": "(생물 분류상의) 종",
    "athletic": "운동의, 운동 경기의",
    "dental": "치아의"
};
const unit4 = {
    "delight": "기쁨, 기쁘게 하다",
    "confident": "자신 있는",
    "gradually": "점차, 서서히",
    "shadow": "그림자, 그늘지게 하다",
    "access": "접근, 이용, 접근하다",
    "announce": "발표하다, 알리다",
    "allow": "허락하다. 인정하다",
    "firm": "확고한, 단단한, 회사",
    "vary": "바꾸다, 변하다, 다르다",
    "injure": "상처를 입히다, 손상시키다",
    "permit": "허용하다, 허락하다",
    "response": "응답, 반응",
    "threat": "위협, 협박",
    "electricity": "전기",
    "disabled": "장애를 가진, 무능력하게 된",
    "lack": "부족, ~이 부족하다",
    "signify": "의미하다, 중요하다",
    "concentrate": "집중하다",
    "emphasize": "강조하다",
    "astronomy": "천문학",
    "flood": "홍수, 범람시키다",
    "fuel": "연료, 연료를 가하다",
    "manufacture": "제조하다, 제조(업), 제품",
    "movement": "움직임, 운동",
    "capable": "~을 할 수 있는, 유능한",
    "combine": "결합시키다, 겸비하다",
    "gene": "유전자",
    "increase": "(수량이)늘다, 증가, 이자",
    "victim": "희생, 희생자",
    "pressure": "압력, 압박, 압력을 가하다",
    "accompany": "동반(동행)하다, 수반하다",
    "frustrate": "좌절시키다",
    "construct": "건설하다",
    "dwindle": "점점 줄어들다, 저하되다",
    "commerce": "상업, 교역",
    "entertain": "즐겁게 하다",
    "predict": "예언하다, 예측하다",
    "apologize": "사과하다",
    "sight": "시야, 광경, 시력",
    "quantity": "양(量)"
};
const unit5 = {
    "conclude": "결론짓다, 끝내다",
    "donate": "기부하다",
    "personality": "개성, 성격, 특색",
    "struggle": "싸우다, 노력하다, 투쟁, 노력",
    "advantage": "유리한 점, 이익",
    "variety": "다양, 다양성",
    "enable": "가능하게 하다",
    "instruction": "지시, 제품 사용 설명서, 가르침",
    "assume": "추정하다, (태도 등을)취하다",
    "attempt": "시도하다, 시도",
    "incredible": "믿을 수 없는, (믿기 어려울 만큼)굉장한",
    "feature": "특징, 특집 기사, 얼굴 생김새, ~을 특징으로 하다, 주연하다",
    "confuse": "혼동하다, 혼란시키다",
    "electronic": "전자의",
    "absorb": "흡수하다, (사람, 마음을)열중시키다",
    "indicate": "가리키다, 나타내다",
    "analyze": "분석하다",
    "stock": "재고품, 저장, 가축, 저장하다, (물품을) 들여놓다",
    "resident": "거주자",
    "labor": "노동, 산고, 노동하다",
    "remark": "의견을 말하다, ~에 주목하다, 의견, 주목",
    "moral": "도덕적인",
    "embarrassed": "당황한",
    "claim": "주장하다, 요구, 주장",
    "reasonable": "논리적인, 분별력이 있는",
    "interrupt": "방해하다, 중단하다",
    "discount": "할인, 할인하다",
    "creature": "생물, 피조물",
    "heal": "치료하다, 낫게하다",
    "establish": "설립하다, 확립하다, 제정하다",
    "revolution": "혁명, 갑작스런 변화, 회전",
    "criticize": "비난하다",
    "convince": "확신시키다, 납득시키다",
    "efficient": "효율적인, 유능한",
    "stranger": "낯선 사람, 문외한",
    "tide": "조수, 흐름",
    "obtain": "획득하다, 통용되다, 행해지다",
    "assist": "도움을 주다",
    "disaster": "재앙, 재난, 재해",
    "terrific": "굉장한, 훌륭한"
};
const unit6 = {
    "specific": "구체적인, 특정한",
    "react": "반응하다, 반작용하다",
    "independent": "독립적인",
    "theory": "이론",
    "qualify": "자격을 얻다",
    "consider": "숙고하다, 고려하다",
    "recall": "상기하다, 철회하다, 회수하다, 상기, 철회, 회수",
    "risk": "위험, 위험을 감수하다",
    "treatment": "취급, 대우, 치료, 치료법",
    "engage": "관여하다, 약속하다, 약혼하다",
    "motivate": "동기를 부여하다",
    "clue": "실마리, 단서",
    "cancer": "암, 악성 종양",
    "elder": "나이가 위인, 연장자",
    "depress": "우울하게 하다, 의기소침(낙담)하게 하다",
    "fascinate": "매료시키다, 마음을 빼앗다",
    "violent": "난폭한, 폭력적인",
    "alarm": "놀람, 경보",
    "edge": "가장자리, 유리함, 날카로움",
    "deserve": "~받을 가치가 있다, ~할 만하다",
    "route": "길, 통로, 향로",
    "psychology": "심리, 심리학",
    "passion": "열정",
    "import": "수입하다, 의미하다, 수입",
    "purchase": "구매하다, 구매",
    "conscience": "양심",
    "pose": "자세를 취하다, 문제를 제기하다, 자세",
    "length": "길이",
    "severe": "심한, 엄격한",
    "decade": "10년, 10년간",
    "occupy": "(시간, 장소를) 차지하다, 전념하다",
    "acquire": "습득하다",
    "interact": "상호 작용하다",
    "brief": "간단한, 간단한 보고, 간단히 알리다",
    "observe": "관찰하다, ~을 보다, 준수하다",
    "poetry": "시, 운문",
    "salary": "급료, 봉급",
    "grain": "곡물, 낟알",
    "meaningful": "의미 있는, 의미심장한",
    "weed": "잡초, 잡초를 제거하다"
};
const unit7 = {
    "survival": "생존",
    "comment": "논평, 주석, 논평하다",
    "leap": "뛰다, 도약하다, 도약",
    "survey": "설문 조사, 조사하다, 둘러보다",
    "typical": "전형적인, 대표적인",
    "mere": "단지, ~에 불과한",
    "mechanic": "기계공",
    "mood": "기분, 분위기",
    "approve": "찬성하다, 승인하다",
    "rural": "시골의",
    "finance": "재정, 재무, 금융, 자금을 조달하다",
    "seek": "찾다, 추구하다, 노력하다",
    "operation": "작업, 운영, 수술",
    "crime": "범죄",
    "awful": "끔찍한, 지독한",
    "series": "연속, 시리즈물",
    "exhausted": "고갈된, 기진맥진한",
    "absolute": "완전한, 절대적인",
    "surround": "둘러싸다",
    "display": "전시하다, 나타내다, 전시",
    "policy": "정책, 수단, 방법",
    "mass": "많은 양, 덩어리, 집단, 대중",
    "committee": "(상급 기관에 소속된) 위원회",
    "accurate": "정확한",
    "arrange": "정리하다, 준비하다, 각색하다",
    "facility": "시설, 편의, 재능",
    "consult": "상담하다, 참고하다",
    "refer": "언급하다, 위탁하다",
    "attach": "붙이다, 첨부하다, 소속시키다",
    "recover": "회복하다, 되찾다",
    "reward": "보상, 보답하다",
    "enormous": "엄청난, 거대한",
    "domestic": "국내의, 가정의",
    "wealth": "부, 재산",
    "elementary": "초보의, 기초적인",
    "gap": "격자, 틈",
    "except": "~을 제외하고는, 제외하다",
    "journey": "여행",
    "plain": "평범한, 명백한",
    "downtown": "도심, 도심의, 도심지에"
};
const unit8 = {
    "previous": "앞의, 이전의",
    "produce": "생산하다, 제조하다",
    "remain": "여전히 ~이다, 남다, 남은 것",
    "break": "깨다, (기기 등을) 고장 내다",
    "slight": "약간의, 경미한",
    "include": "포함하다",
    "delay": "연기하다, 미루다, 지연",
    "file": "서류철, <컴퓨터> 파일, 서류철을 작성하다, (소송 등을) 제기하다",
    "ethic": "윤리",
    "instant": "즉각의, 즉석의, 순간",
    "reveal": "드러내다, 폭로하다",
    "breed": "낳다, 양육하다",
    "leisure": "여가, 자유시간, 한가한",
    "urban": "도시의",
    "witness": "목격자, 증인, 목격하다",
    "admit": "인정하다, 입장(입학)을 허락하다.",
    "muscle": "근육, 힘, 강제",
    "device": "장치, 고안, 방책",
    "suppose": "가정하다, 추측하다",
    "owe": "빚지고 있다, (명예·성공 등을) ~에 돌리다",
    "intend": "~할 작정이다, 의도하다",
    "aspect": "관점, 양상, 면",
    "potential": "잠재적인, 잠재력",
    "award": "수여하다, 상",
    "preserve": "보존하다, 보호하다",
    "spot": "지점, 얼룩, 발견하다, 얼룩지게 하다",
    "underground": "지하의, 비밀의, 지하",
    "consequence": "결과, 중요성",
    "target": "목표, 표적, 목표로 삼다",
    "unless": "~이 아닌 한, 만약 ~이 아니면",
    "accomplish": "이루다, 성취하다",
    "adopt": "채택하다, 입양하다",
    "unique": "독특한, 유일한",
    "slip": "미끄러지다, 살수하다, 종이 조각",
    "civilization": "문명",
    "row": "열, 줄, 배를 젓다",
    "horizon": "수평선, 지평선",
    "atmosphere": "대기, 분위기",
    "label": "꼬리표, 상표, 라벨을 붙이다, ~을…이라고 부르다",
    "decorate": "장식하다, ~에게 훈장을 주다"
};
const unit9 = {
    "identify": "~임을 확인하다, 식별하다, 동일시하다",
    "standard": "기준, 표준, 기준의, 표준의",
    "scale": "규모, 저울, 비늘",
    "evident": "명백한, 평범한",
    "seldom": "거의 ~않는",
    "secretary": "비서, 서기관, 장관",
    "basis": "기초, 원리",
    "automatic": "자동적인, 기계적인",
    "region": "지역",
    "rise": "상승, 오르다, 일어나다",
    "addict": "중독시키다. 중독자",
    "disappoint": "실망시키다",
    "artificial": "인공적인, 인조의",
    "possess": "소유하다, ~의 마음을 사로잡다",
    "substance": "물질, 본질, 실체",
    "realistic": "현실적인, 현실주의의",
    "encounter": "(우연히) 만나다, 마주침",
    "differ": "다르다. 의견을 달리하다",
    "principle": "원칙, 원리",
    "memorize": "기억하다",
    "physics": "물리학",
    "evaluate": "평가하다",
    "tremendous": "굉장한, 무시무시한",
    "application": "적용, 신청",
    "vote": "투표, 투표하다",
    "spread": "퍼짐, 확산, 퍼지다, 펼치다",
    "impact": "충격, 영향, 충격을 주다, 영향을 주다",
    "cooperate": "협력하다",
    "emit": "(빛, 열 소리등을) 방출하다",
    "request": "요청, 요청하다",
    "guarantee": "보증하다, 보증",
    "resist": "저항하다",
    "fulfill": "달성하다, 이행하다. 실현하다",
    "stink": "역겹다, 악취를 풍기다, 악취",
    "grant": "승인하다, 수여하다",
    "rely": "의지하다, 믿다",
    "permanent": "영원한, 영구적인",
    "emergency": "비상사태",
    "rid": "제거하다",
    "theme": "주제, 화제, 논제"
};
const unit10 = {
    "hesitate": "주저하다, 망설이다",
    "location": "장소, 위치",
    "restrict": "제한하다, 한정하다",
    "organism": "유기체, 생물, 생명체",
    "resolve": "결심하다, 해결하다, 분해하다",
    "offer": "제공하다, 제안하다",
    "distribute": "분배하다, 분포시키다",
    "rainforest": "(열대)우림",
    "circumstance": "상황, 환경",
    "interpret": "해석하다. 통역하다",
    "suitable": "적절한, 적합한",
    "curve": "곡선(길), 속임수",
    "annoy": "괴롭히다, 귀찮게 하다",
    "frighten": "겁먹게 하다",
    "estimate": "견적, 평가, 평가하다",
    "refuse": "거절하다",
    "adventure": "모험, 위험에 빠뜨리다",
    "entrance": "입장, 입구, 입학",
    "persuade": "설득하다",
    "perceive": "인지하다. 인식하다.",
    "recite": "암송하다",
    "gather": "모으다",
    "cabin": "오두막집, 객실, 선실",
    "gear": "장비, 기어, 맞게 조정하다",
    "ray": "광선",
    "release": "놓아주다, 방출하다, 발표하다, 석방, 발표",
    "rank": "등급, 지위, 매기다, 등급을 차지하다",
    "symphony": "교향곡, (소리의) 조화",
    "envy": "부러움, 부러워하다",
    "corporate": "회사의, 법인의",
    "alternative": "대안, 대안의",
    "retire": "은퇴하다",
    "appeal": "호소하다, 항의하다, 관심을 끌다, 호소, 항의, 매력",
    "identical": "동일한, 일란성의",
    "investment": "투자",
    "autograph": "서명, 서명하다",
    "slave": "노예",
    "harm": "손해, 손상, 해치다",
    "authority": "권위, 당국",
    "innocence": "결백, 무죄, 순진"
};
const unit11 = {
    "receive": "받다",
    "infant": "유아, 유아의, 미발달의",
    "calculate": "계산하다",
    "charity": "자비, 자선 단체, 구호물자",
    "accept": "받아들이다, (설명, 학성등을)인정하다",
    "depend": "의지하다",
    "whereas": "~인 반면에",
    "broad": "넓은, 광범위한, (빛 등이) 가득한",
    "treat": "여기다, 대우하다, 처리하다, 치료하다",
    "ignorant": "무식한, 모르는",
    "pure": "순수한",
    "extinct": "멸종된, 꺼진, 사라진",
    "household": "가정, 가정(가족)의",
    "refund": "반환, 환불, 환불하다",
    "continue": "계속하다",
    "institute": "연구소, 협회, 설립하다, 제정하다",
    "lately": "최근에",
    "ashamed": "부끄러워하는",
    "dense": "조밀한, 밀집한",
    "rescue": "구조하다, 구조",
    "destination": "목적지",
    "expand": "확장하다",
    "compete": "경쟁하다",
    "evolution": "진화",
    "hire": "고용하다",
    "genuine": "진짜의, 성실한",
    "status": "상태, 지위, 현상",
    "military": "군대의, 군대",
    "logic": "논리, 논리학",
    "gravity": "중력",
    "isolate": "고립시키다",
    "commit": "(죄를)저지르다, 전념(충실)하다, 맡기다",
    "sum": "총합, 합계",
    "conserve": "보존하다, 보호하다, 아끼다, 아껴쓰다.",
    "concept": "개념",
    "swing": "흔들(리)다, 진동하다, 그네",
    "sensible": "분별있는, 현명한",
    "marriage": "결혼, 혼인",
    "reproduce": "재생하다, 복제하다, 번식하다",
    "tone": "어조, 말투, 음, 색조"
};
const unit12 = {
    "cancel": "취소하다",
    "return": "돌아오다, 돌려주다, 귀환, 반납, 수익",
    "invitation": "초대, 초대장",
    "precise": "정확한",
    "formal": "공식적인, 정식의",
    "apparent": "분명한, 명백한",
    "departure": "출발",
    "visual": "시각의",
    "current": "현재의, 해류, 흐름",
    "agriculture": "농업",
    "leak": "새는 구멍, 새다, 누설하다",
    "portion": "일부, 부분, 분할하다",
    "trend": "추세, 경향",
    "particle": "입자, 극소량",
    "rite": "(종교적) 의식, 의례",
    "distinct": "별개의, 뚜렷한",
    "component": "(구성)요소, 구성하는",
    "poverty": "빈곤, 가난",
    "sculpture": "조각, 조각하다",
    "descend": "내려오다, 물려주다",
    "universal": "보편적인, 우주의",
    "surface": "표면, 수면, 지면",
    "eager": "갈망하는",
    "legal": "법률의, 합법의",
    "annual": "연례의, 1년의, 1년간의",
    "trap": "함정, 덫을 놓다, 막다",
    "demonstrate": "논증하다, 설명하다, 시위하다, 보여 주다",
    "companion": "동료, 동반자",
    "democracy": "민주주의, 민주주의 국가",
    "mature": "성숙한, 익은, 지불 만기의, 성숙해지다",
    "brilliant": "훌륭한, 명석한",
    "faith": "신념, 믿음",
    "aim": "겨냥하다, 조준",
    "spare": "여분의, 검소한, 용서하다, 남겨주다",
    "transfer": "이동하다, 옮기다, 갈아타다",
    "oppose": "반대하다",
    "desperate": "필사적인, 절망적인",
    "remote": "멀리 떨어진, 희박한, 드문",
    "offend": "기분을 상하게 하다, (범죄를) 저지르다",
    "awake": "깨어있는, 깨우다, 깨다"
};
const unit13 = {
    "option": "선택, 선택권",
    "insight": "통찰, 통찰력",
    "achieve": "(목적을) 달성하다, (명성을) 얻다",
    "civil": "시민의, 민간의",
    "pause": "중단, 중단하다, 잠시 멈추다.",
    "prove": "입증하다, (~임이) 판명되다",
    "lecture": "강의, 강의를 하다",
    "minor": "사소한, 소수의, 미성년자, 부전공, 부전공하다",
    "duty": "의무, 관세",
    "vigor": "활력",
    "organize": "조직하다, 구성하다, 정리하다",
    "chief": "주요한, 우두머리의, 우두머리",
    "complicated": "복잡한",
    "digest": "소화하다, (완전히) 이해하다, 요약",
    "shortage": "부족, 결함",
    "laboratory": "실험실, 실험(실)의",
    "arrive": "도착하다",
    "generous": "관대한, 넉넉한",
    "laundry": "세탁물",
    "transform": "변형시키다, 변환하다",
    "discipline": "훈련, 규율, 징계, 훈련(단련)하다, 징계하다",
    "forbid": "금지하다",
    "ultimate": "궁극적인, 최후의",
    "thrive": "번영하다, 발전하다, 잘 되다",
    "conversation": "대화, 회담, 좌담",
    "bet": "돈을 걸다, 내기를 하다, (~이)틀림없다, 내기",
    "royal": "왕족의, 왕의",
    "ruin": "파멸, 파산, 망치다, 파멸(파산)시키다",
    "worship": "예배하다, 숭배하다, 예배, 숭배",
    "evil": "사악한, 악",
    "scarce": "부족한, 드문",
    "afterward": "나중에, 그 후에",
    "client": "고객, (변호사 등의) 의뢰인",
    "insure": "보험을 계약하다, 안전하게 하다",
    "fancy": "공상, (일시적인)기호, 공상하다, 화려한",
    "surgery": "외과수술",
    "assign": "할당하다, 지정하다",
    "regulate": "규제하다, 조절하다",
    "shelf": "선반",
    "utility": "유용(성), (수도, 가스 등의) 공익사업"
};
const unit14 = {
    "necessity": "필수, 필수품, 필요",
    "yield": "생산하다, 양도하다, 굴복하다, 수확(물)",
    "decline": "감소, 쇠퇴, 감소하다, 쇠퇴하다, (정중히) 거절하다",
    "coincidence": "우연의 일치, 동시에 일어난 사건",
    "aside": "한쪽으로, 제쳐 두고",
    "contemporary": "동시대의, 현대의",
    "bless": "축복하다, 감사하다",
    "explain": "설명하다",
    "prior": "이전의, 우선하는",
    "tolerate": "참다, 용인하다",
    "measure": "측정하다, 측정, 수단",
    "abstract": "추상적인, 추상, 개요",
    "cottage": "오두막집",
    "correct": "올바른, 정확한, 바로잡다, 정정하다",
    "confirm": "입증(확인)하다, (결심을)굳게하다",
    "imitate": "모방하다",
    "prey": "먹이, 희생자",
    "defeat": "패배시키다, 패배",
    "illustrate": "설명하다, 예증하다, 삽화를 넣다",
    "fuse": "퓨즈, 도화선, 융합하다",
    "pupil": "학생, 눈동자",
    "intellect": "지성",
    "spice": "향신료, 양념",
    "tempt": "유혹하다, (관심을) 끌다",
    "inspire": "영감을 주다, 고무시키다, 격려하다",
    "dine": "만찬을 대접하다, 식사하다",
    "literally": "문자 그대로",
    "appropriate": "적절한",
    "resort": "휴양지, 의지, 의지하다, 자주 가다",
    "grab": "움켜쥐다, 움켜쥠",
    "propose": "제안하다, 청혼하다",
    "wreck": "난파선, 사고, 난파시키다",
    "document": "문서, 서류, 기록하다",
    "suspect": "의심하다, 용의자",
    "alien": "외국인, 외계인, 외국의, 이질적인",
    "prohibit": "금지하다",
    "install": "설치하다",
    "triumph": "승리, 승리하다",
    "scholarship": "학문, 장학금",
    "execute": "실행하다, 처형하다"
};
const unit15 = {
    "ensure": "확실하게 하다, 보증하다",
    "receipt": "영수증",
    "defect": "결점, (국가, 당 등을) 버리다",
    "trait": "특성, 특징",
    "modest": "겸손한, 알맞은",
    "virtual": "가상의, 사실상의",
    "compare": "비교하다",
    "address": "연설하다, 연설, 인사말",
    "inner": "내부의",
    "contrary": "반대의, 불리한, 반대의 것",
    "split": "찢다, (세로로) 쪼개다, 쪼개진, 분열",
    "supervise": "감독하다, 관리하다, 통제하다",
    "inhabit": "살다, 거주하다",
    "appear": "나타나다",
    "commute": "통근, 통근하다",
    "earthquake": "지진, (사회, 정치적) 대변동",
    "enroll": "입학하다, 등록하다",
    "debate": "토론, 토론하다",
    "abandon": "버리다, 포기하다",
    "conquer": "정복하다, 극복하다",
    "nevertheless": "그럼에도 불구하고",
    "seal": "도장, 봉인, 바다표범, 봉인하다",
    "greed": "탐욕",
    "contract": "계약하다, 수축하다, 계약서",
    "nutrition": "영양",
    "retail": "소매, 소매하다",
    "prejudice": "편견, 선입관",
    "register": "등록하다, 기재하다, 등록",
    "agency": "대리점",
    "nurture": "양육하다, 교육하다, 양육, 교육",
    "priest": "성직자",
    "elegant": "고상한, 우아한",
    "impose": "부과하다, 강요하다",
    "arise": "발생하다, 생겨나다",
    "modify": "변형하다, 수정하다",
    "masterpiece": "명작, 대작",
    "harsh": "거친, 가혹한",
    "drought": "가뭄",
    "criteria": "(pl.) 기준, 표준",
    "extraordinary": "비범한, 놀라운"
};
const unit16 = {
    "general": "일반적인, (육군, 공군, 해병대) 대장",
    "spill": "엎지르다, 흘리다, 엎질러짐, 유출",
    "usual": "보통의, 통상의",
    "routine": "일상적인 일, 일과, 일상적인",
    "eliminate": "제거하다, 삭제하다",
    "deny": "부인하다, 거절하다",
    "scream": "절규하다, 비명 지르다, 소리치다, 비명, 절규",
    "sensitive": "민감한, 예민한, 세심한",
    "swallow": "삼키다, 삼킴, 제비",
    "glare": "(눈부시게) 빛나다, 노려보다, 눈부신 빛, 노려봄",
    "tragic": "비극의, 비참한",
    "deprive": "박탈하다",
    "conscious": "의식하고 있는, 의도적인",
    "interfere": "방해하다, 간섭하다",
    "temporary": "일시적인, 임시의",
    "council": "협의회, 회의",
    "adolescent": "청소년, 청소년기의",
    "associate": "연관짓다, 교제하다, 동료",
    "arctic": "북극의",
    "capture": "붙잡다, 포획하다, 포획",
    "dilute": "묽은, 희석시키다",
    "figure": "생각(판단)하다, 계산하다, 수치, 계산, 형체",
    "dim": "흐릿한, 어두운, (불빛이) 흐려지다",
    "warehouse": "창고",
    "crew": "승무원",
    "barrier": "장벽, 장애물",
    "tradition": "전통, 관습",
    "pedestrian": "보행자, 보행자의",
    "glance": "흘긋 보다, 흘긋 봄",
    "irritate": "짜증나게 하다, 화나게 하다",
    "cruel": "잔인한, 고통을 주는",
    "fold": "접다, 포개다, 주름, (동물의) 우리",
    "trial": "재판, 실험, 시도",
    "tribe": "부족, 종족",
    "profound": "깊은, 심오한",
    "distinguish": "구별하다, 식별하다",
    "errand": "심부름, 잡일",
    "welfare": "복지",
    "statement": "진술, 성명서",
    "prevail": "우세하다, 만연하다"
};
const unit17 = {
    "widespread": "널리 퍼진",
    "result": "결과, (결과로서) 생기다",
    "fade": "사라지다",
    "progress": "진보하다, 전진하다, 진전, 진보",
    "weapon": "무기, 병기",
    "drastic": "격렬한, 과감한",
    "reinforcement": "강화, 보강",
    "wonder": "궁금해 하다, 놀라다, 경탄, 경이",
    "pile": "쌓아 올린 더미, 많은 양, 쌓아 올리다, 축적하다",
    "protect": "보호하다",
    "infection": "감염, 전염(병)",
    "stiffen": "굳어지다",
    "endanger": "위험에 빠뜨리다",
    "adjust": "조절하다, 조정하다",
    "peer": "동료, 또래",
    "renew": "새롭게 하다, 갱신하다",
    "germ": "미생물, 세균",
    "atom": "원자",
    "realize": "깨닫다, 실현하다",
    "enrich": "풍성하게 하다, 부유하게 하다",
    "noble": "귀족의, 고결한",
    "repair": "수선(수리)하다, (건강 등을) 회복하다, 수선(수리), 회복",
    "candidate": "후보자",
    "ideal": "이상적인, 이상",
    "crop": "작물, 수확",
    "ethnic": "인종의, 민족의",
    "foretell": "예언하다, 예고하다",
    "wholesale": "도매, 도매의",
    "debt": "빚, 부채",
    "representative": "대표, 국회의원(R~), 대표하는",
    "shift": "변화, 이동, 교대, 바꾸다, 이동하다",
    "excess": "초과, 초과량, 과도함, 초과한, 여분의",
    "strict": "엄한, 엄격한",
    "appliance": "(가정용) 기구, 장치",
    "furthermore": "게다가, 더욱이",
    "command": "명령, 지배력, 명령하다, 지휘하다",
    "ecosystem": "생태계",
    "fame": "명성, 유명인사",
    "oral": "구두의, 구술의",
    "drift": "표류, 표류하다"
};
const unit18 = {
    "avoid": "피하다",
    "outstanding": "뛰어난, 두드러진, 미해결의",
    "mislead": "잘못 인도하다, 오해하게 하다",
    "dedicate": "헌납하다, 바치다",
    "initial": "처음의, 초기의, 머리글자(이니셜)",
    "sink": "가라앉다",
    "entire": "전체의, 완전한, 전부, 전체",
    "confront": "직면하다",
    "beard": "턱수염",
    "haste": "급함, 서두름",
    "crush": "으깨다, 밀어 넣다",
    "destiny": "운명",
    "hardship": "고난, 어려움",
    "escape": "탈출하다, 벗어나다, 탈출, 도망",
    "valid": "타당한, 유효한",
    "dispose": "배치하다, 처리하다, 경향을 갖게 하다",
    "exist": "존재하다, 살아가다",
    "optimal": "최상의, 최적의",
    "hydrogen": "수소",
    "perspective": "관점, 견해, 원근법, 전망",
    "thread": "실, 실을 꿰다",
    "dynasty": "왕조, 왕가",
    "scatter": "흩뿌리다, 분산시키다",
    "gamble": "도박하다, 모험하다, 도박, 모험",
    "temper": "성질, 기질, 완화시키다",
    "undoubtedly": "의심할 여지없이, 확실히",
    "raft": "뗏목, 고무보트",
    "minimal": "최소의, 아주 적은",
    "soak": "적시다, 젖다, 흡수하다",
    "craft": "(수)공예, 기술, 선박, 비행기",
    "cease": "그만두다, 중지하다",
    "review": "재검토, 논평, 재검토하다",
    "ceiling": "천장, 상한선",
    "unify": "통합하다, 통일하다",
    "combat": "싸우다, 전투",
    "bump": "부딪치다, 충돌, 혹",
    "primary": "주요한, 최초(초기)의",
    "genre": "장르, 유형, 형식",
    "erase": "지우다, 없애다",
    "doom": "~할 운명이다, 운명, 비운, 파멸"
};
const unit19 = {
    "vital": "필수적인, 중요한, 생명 유지와 관련된",
    "incident": "일어난 일, 사건, 일어나기 쉬운",
    "session": "시간, 기간, 회의, (대학의) 학기",
    "obvious": "명백한, 분명한",
    "moderate": "온건한, 적당한",
    "budget": "예산, 예산안",
    "graze": "풀을 뜯다, 방목하다",
    "fragile": "부서지기 쉬운",
    "myth": "신화, 사회적 통념",
    "fur": "부드러운 털, 모피",
    "indifferent": "무관심한",
    "strain": "긴장시키다, 팽팽하게 하다, (너무 써서)상하게 하다, 긴장",
    "ingredient": "재료, 성분",
    "dismiss": "해고하다, 해산시키다, 묵살하다",
    "geometry": "기하학",
    "glacier": "빙하",
    "urge": "촉구하다, 강요하다",
    "celebrity": "명성, 유명 인사",
    "antique": "옛날의, 고대의, 고풍의, 골동품",
    "profit": "이익, 이윤, 이익을 얻다",
    "sphere": "구체, 구",
    "inherit": "상속하다, (유전으로)물려받다",
    "disgrace": "불명예, 수치",
    "crawl": "기어가다, 서행하다, 기어가기, 서행",
    "scratch": "긁다, 할퀴다, 긁힌, 자국, 찰과상",
    "diabetes": "당뇨병",
    "congestion": "밀집, 혼잡",
    "constitute": "구성하다, 제정하다, 설립하다",
    "flow": "흐르다, 흐름",
    "investigate": "조사하다, 수사하다",
    "barter": "물물교환하다, 물물교환, 교역품",
    "circular": "원의, 순환의",
    "chilly": "쌀쌀한, 냉담한",
    "ancestor": "조상, 선조",
    "fierce": "사나운, 맹렬한",
    "vague": "막연한, 모호한, 흐릿한",
    "rough": "거친, 난폭한, 대강의",
    "content": "만족하는, 내용(물), 목차",
    "obstacle": "장애물, 방해가 되는 것",
    "editorial": "사설, 논설, 편집자의"
};
const unit20 = {
    "abolish": "폐지하다",
    "assure": "보증하다, 확실하게 하다",
    "form": "형태, 종류, 형성하다",
    "gender": "성, 성별",
    "innovation": "혁신",
    "opponent": "반대자, 상대, 반대하는",
    "present": "현재의, 현재, 선물, 제출하다, 나타내다",
    "fertile": "비옥한, 기름진",
    "emperor": "황제",
    "dwell": "살다, 거주하다",
    "chore": "집안일, 허드렛일",
    "rehearsal": "리허설, 예행연습",
    "fossil": "화석",
    "glitter": "반짝이다, 반짝임",
    "carve": "조각하다, 새기다",
    "decay": "부패하다, 쇠퇴하다, 부패, 쇠퇴",
    "protein": "단백질",
    "backward": "후방에, 뒤쪽으로, 거꾸로",
    "translate": "번역하다, 옮기다",
    "refresh": "상쾌하게 하다, 새롭게 하다",
    "tissue": "(생물의 근육, 신경 등의) 조직",
    "lord": "군주",
    "substitute": "대리자, 대체물, 대체하다",
    "scan": "정밀 검사하다, 유심히 쳐다보다",
    "pottery": "도자기, 도예",
    "layer": "층, 겹",
    "property": "재산, 소유물, 부동산",
    "justify": "정당화하다",
    "polish": "닦다, 윤내다, (문장 등을) 다듬다",
    "flavor": "맛, 맛을 내다",
    "imprint": "(도장 등을) 찍다, 감명시키다, 찍은 자국, 인상",
    "heritage": "유산, 세습 재산",
    "strive": "노력하다, 애쓰다, 투쟁하다",
    "radiant": "빛나는, 아주 밝은",
    "exclaim": "(감탄하며) 외치다",
    "asset": "자산, 재산",
    "portray": "묘사하다, 설명하다, 초상을 그리다",
    "administer": "관리(운영)하다, 집행하다, 주다",
    "wage": "급료",
    "subscribe": "정기 구독하다"
};
const unit21 = {
    "merit": "장점, 공로, ~을 받을 만하다",
    "launch": "발사하다, (새로운 일을) 시작하다, 출시하다, 발사, 개시, 출시",
    "conference": "회담, 회의",
    "accuse": "고발하다, 비난하다",
    "enhance": "향상시키다",
    "intimate": "친밀한",
    "reception": "환영회, 접수",
    "overwhelm": "압도하다, 당황하게 하다",
    "apply": "적용하다",
    "majesty": "위엄, 장엄, 왕(M-)",
    "shrug": "(어깨를) 으쓱하다",
    "vicious": "사악한, 악의 있는",
    "cherish": "소중히 하다",
    "eternal": "영원한",
    "shrink": "축소하다, 수축하다",
    "colleague": "동료",
    "transmit": "전달하다",
    "discard": "버리다, 처분하다",
    "copper": "구리, 구리의, 구릿빛의",
    "orbit": "궤도, 궤도를 그리며 돌다",
    "famine": "굶주림, 기아",
    "pill": "알약",
    "immune": "면역성의, 면제된",
    "raw": "날것의, 가공하지 않은",
    "superior": "우월한, 상사",
    "string": "끈, 줄, 일련",
    "cope": "대처하다, 잘 처리하다",
    "loan": "대출, 대출금, 대출하다",
    "obedient": "순종하는, 유순한",
    "procedure": "절차, 과정",
    "bond": "결속, 속박, 약정, 채권",
    "angle": "각도, 모서리",
    "subtle": "미묘한, 교묘한",
    "depict": "묘사하다, 그리다",
    "radical": "과격한, 급진적인, 근본적인, 급진주의자",
    "caution": "조심, 주의, 주의하다",
    "persist": "고집하다, 지속하다",
    "reverse": "역, 반대, 역의, 반대의, 되돌리다",
    "cattle": "(집합적) 소",
    "therapy": "치료, 요법"
};
const unit22 = {
    "experience": "경험, 체험, 경험하다",
    "strategy": "전략",
    "attract": "(주의, 흥미 등을) 끌다",
    "hence": "그러므로, 지금부터",
    "architecture": "건축, 건축물",
    "territory": "영토, 영역",
    "wilderness": "황무지, 황야",
    "category": "범주",
    "funeral": "장례식, 장례의",
    "prefer": "선호하다",
    "outcome": "결과",
    "humiliation": "창피함, 굴욕",
    "ban": "금지하다, 금지",
    "flush": "(얼굴이) 붉어지다, 물이 쏟아져 나오다",
    "omit": "생략하다, 빼다",
    "despair": "절망, 절망하다",
    "alert": "기민한, 경계하는, 경계(태세), 경고하다",
    "compact": "소형의, 조밀한, 꽉 채우다",
    "likewise": "마찬가지로, 게다가",
    "astonish": "놀라게 하다",
    "panic": "갑작스러운 공포, 공황, 공황적인",
    "optimistic": "낙관적인, 낙천적인",
    "murder": "살인, 살인하다",
    "fundamental": "근본적인, 기본적인, 근본",
    "loyal": "충성스러운, 성실한",
    "humid": "(날씨가) 습기 있는, 눅눅한",
    "pretend": "~인 척하다, 주장하다",
    "graduate": "졸업하다, 졸업생, 대학원 학생",
    "delicate": "섬세한",
    "inflate": "부풀리다, 과장하다, (물가 등을) 인상하다",
    "adequate": "적당한",
    "physician": "의사, 내과 의사",
    "joint": "공동의, 연합의, 이음매, 관절",
    "via": "~을 거쳐서(경유해서), ~에 의하여",
    "passage": "통로, 통과, (인용문의) 한 절",
    "vessel": "(물건을 담는) 용기, 배, 선박, 혈관",
    "restore": "회복하다, 복구하다, 돌려주다",
    "passive": "수동적인, 수동형의",
    "marble": "대리석, 구슬, 대리석의",
    "classify": "분류하다"
};
const unit23 = {
    "prepare": "준비하다",
    "transaction": "거래, 처리",
    "sufficient": "충분한",
    "stable": "안정된, 마구간",
    "concern": "관련되다, 걱정하게 하다, 걱정, 관심사",
    "sympathy": "동정, 공감",
    "principle": "주요한, 제1의, (단체의) 장, 주역",
    "by-product": "부산물",
    "anxiety": "걱정, 불안, 열망",
    "edible": "먹을 수 있는, 식용의",
    "federal": "연방의, 연합의",
    "suffer": "고통 받다, 겪다",
    "trivial": "사소한",
    "tablet": "(의학) 정제, 알약, (평평한) 판",
    "trade": "교환하다, 무역",
    "liquid": "액체, 액체의",
    "contend": "싸우다, 주장하다, 경쟁하다",
    "anticipate": "예상하다, 기대하다",
    "outlook": "전망, 조망",
    "desert": "사막, 사막의, 불모의, 버리다, 도주하다",
    "infinite": "무한한",
    "roam": "배회하다, 돌아다니다",
    "decent": "제대로 된, 품위 있는",
    "behalf": "이익, 자기편",
    "distortion": "왜곡, 찌그러뜨림",
    "bud": "싹, 싹트다",
    "symbolic": "상징적인",
    "municipal": "지방(지자체)의, 시의",
    "phenomenon": "현상, 사건, 비범한 인물",
    "devote": "(노력, 시간 등을) 바치다",
    "peasant": "농민, 소작농",
    "diminish": "감소하다",
    "jealous": "질투하는",
    "exclude": "배제하다, 제외하다",
    "flexible": "융통성 있는, 유연한",
    "tenant": "세입자, 주민",
    "worthwhile": "~할 가치가 있는",
    "pavement": "보도, 포장도로",
    "nominate": "(후보자로) 지명(추천)하다, 임명하다",
    "sacred": "신성한, 성스러운"
};
const unit24 = {
    "support": "지지하다, 받치다, 부양하다, 지지, 지탱함, 부양",
    "revise": "개정하다",
    "suggest": "제안하다, 암시하다",
    "control": "지배하다, 제어하다, 지배, 제어",
    "mammal": "포유동물",
    "internal": "내부의",
    "resent": "분개하다, 화를 내다",
    "abrupt": "갑작스러운",
    "diverse": "다른, 다양한",
    "refine": "정제하다, 개선하다",
    "dynamic": "동적인, 역학의",
    "nerve": "신경",
    "prompt": "즉각적인, 촉구하다, 자극하다",
    "suspend": "매달다, 중지하다",
    "industry": "산업, 공업",
    "iceberg": "빙산",
    "monetary": "화페의",
    "superb": "최고의, 훌륭한",
    "gloom": "어둠, 우울",
    "distraction": "주의 산만, (정신을) 산만하게 하는 것, 기분 전환",
    "collapse": "무너지다, 붕괴하다, 붕괴",
    "trigger": "촉발하다, 유발하다, 방아쉬, 계기",
    "martial": "전쟁의, 군대의",
    "monologue": "독백",
    "deliberate": "의도적인, 신중한, 숙고하다",
    "plot": "줄거리, 음모, 음모를 꾸미다",
    "rod": "막대기, 회초리",
    "partial": "부분적인",
    "mutual": "서로의, 공통의",
    "priceless": "대단히 귀중한",
    "fate": "운명",
    "pursue": "추구하다, 쫓다",
    "Atlantic": "대서양, 대서양의",
    "weird": "이상한, 기묘한",
    "booth": "칸막이한 공간, 부스, 노점",
    "prescribe": "규정하다, (약을) 처방하다",
    "erupt": "분출하다, 폭발하다",
    "insult": "모욕하다, 모욕",
    "gaze": "뚫어지게 보다, 응시하다",
    "supreme": "최고, 최고의"
};
const unit25 = {
    "context": "경주(경쟁)하다, 질주하다, 경주",
    "complete": "완전한, 완벽한, 완료된, 완료하다",
    "race": "경주(경쟁)하다, 질주하다, 경주",
    "dominate": "지배하다",
    "vehicle": "탈것, 운송 수단",
    "complain": "불평하다, 항의하다",
    "brochure": "소책자, 브로셔",
    "force": "힘, 영향력, 강요하다",
    "nest": "둥지, 보금자리, 둥지를 틀다, (둥지에서) 살다",
    "gain": "얻다, 이익",
    "curriculum": "교육 과정, 커리큘럼",
    "sew": "꿰매다, 바느질하다",
    "masculine": "남자의, 남자다운",
    "frown": "눈살을 찌푸리다, 찡그린 얼굴",
    "astound": "놀라게 하다",
    "dictator": "독재자, 구술하는 사람",
    "assessment": "평가, 판단",
    "crucial": "중대한, 결정적인",
    "paralysis": "마비",
    "deck": "갑판",
    "cheer": "환호, 갈채, 환호(성원)하다",
    "miserable": "비참한, 불쌍한",
    "tease": "괴롭히다, 약올리다",
    "aggressive": "공격적인, 적극적인",
    "cure": "치료하다, 해결하다, 치유, 회복",
    "attribute": "~의 결과로 여기다, 속성",
    "foster": "육성하다, 촉진시키다, 수양의, 위탁의",
    "psychologist": "심리학자",
    "postpone": "연기하다, 뒤로 미루다",
    "rob": "훔치다, 강탈하다",
    "abuse": "남용, 욕설, 학대, 남용하다, 학대하다",
    "unemployed": "실업의, 실직한",
    "breakdown": "고장, 쇠약",
    "disguise": "변장하다, 숨기다, 변장, 은폐",
    "blueprint": "청사진",
    "rear": "뒤, 뒤의, 후방의, 기르다, 일으키다",
    "output": "생산(량), 산출(량)",
    "sermon": "설교",
    "sprout": "싹이트다, 자라나다, 싹",
    "tin": "양철, 주석"
};
// 나머지 유닛 데이터를 추가하세요 (unit3 ~ unit50)
// 모든 유닛 데이터를 window 객체에 추가
for (let i = 1; i <= 25; i++) {
    window[`unit${i}`] = eval(`unit${i}`);
}

let mergedObject = {}; // 전역 변수로 선언

function generateQuiz() {
    const startNumber = parseInt(document.getElementById('startInput').value);
    const endNumber = parseInt(document.getElementById('endInput').value);

    if (isNaN(startNumber) || isNaN(endNumber) || startNumber < 1 || endNumber > 25 || startNumber > endNumber) {
        alert("Please enter valid unit numbers between 1 and 25.");
        return;
    }

    const objectsArray = [];
    for (let i = startNumber; i <= endNumber; i++) {
        const unit = window[`unit${i}`];
        if (unit) {
            objectsArray.push(unit);
        }
    }

    mergedObject = Object.assign({}, ...objectsArray); // 전역 변수에 할당
    const shuffledKeys = shuffleArray(Object.keys(mergedObject));
    const quizContainer = document.querySelector('.quiz-container');
    quizContainer.innerHTML = '';

    shuffledKeys.forEach((key, index) => {
        const correctAnswer = mergedObject[key];
        const options = [correctAnswer, ...getRandomOptions(mergedObject, correctAnswer)];
        const shuffledOptions = shuffleArray(options);

        const questionHtml = `
            <div>
                <strong>${index + 1}. ${key}</strong>
                <select name="question${index + 1}" class="pl">
                    <option value="0" selected>Select the correct meaning</option>
                    ${shuffledOptions.map(option => `<option value="${option}">${option}</option>`).join('')}
                </select>
            </div>
        `;

        quizContainer.insertAdjacentHTML('beforeend', questionHtml);
    });

    document.getElementById('submitBtn').style.display = 'block';
}

function getRandomOptions(obj, correctAnswer) {
    const values = Object.values(obj).filter(value => value !== correctAnswer);
    const randomValues = [];

    while (randomValues.length < 3) {
        const randomValue = values[Math.floor(Math.random() * values.length)];
        if (!randomValues.includes(randomValue)) {
            randomValues.push(randomValue);
        }
    }

    return randomValues;
}

function shuffleArray(array) {
    const shuffledArray = array.slice();
    for (let i = shuffledArray.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [shuffledArray[i], shuffledArray[j]] = [shuffledArray[j], shuffledArray[i]];
    }
    return shuffledArray;
}

function gradeQuiz() {
    const quizContainer = document.querySelector('.quiz-container');
    const selects = quizContainer.querySelectorAll('select');
    let correctCount = 0;
    const incorrectAnswers = [];

    selects.forEach((select, index) => {
        const selectedValue = select.value;
        const questionKey = select.previousElementSibling.textContent.split('. ')[1];
        const correctAnswer = mergedObject[questionKey];

        if (selectedValue === correctAnswer) {
            correctCount++;
        } else {
            incorrectAnswers.push({ questionKey, correctAnswer });
        }
    });

    const totalQuestions = selects.length;
    const scorePercentage = (correctCount / totalQuestions) * 100;
    document.getElementById('results').innerHTML = `
        <div class="centered">You scored ${correctCount} out of ${totalQuestions} (${scorePercentage.toFixed(2)}%)</div>
        <br><br>
        <strong>Incorrect Answers:</strong>
        <table>
            <thead>
                <tr>
                    <th>English Word</th>
                    <th>Correct Meaning</th>
                </tr>
            </thead>
            <tbody>
                ${incorrectAnswers.map(answer => `
                    <tr>
                        <td>${answer.questionKey}</td>
                        <td class="toggle-meaning" onclick="toggleMeaning(this)">${answer.correctAnswer}</td>
                    </tr>
                `).join('')}
            </tbody>
        </table>
    `;
}
